### ISSUE TITLE
[Feature / Research] Shadow Spline Format Size Saving 

### ISSUE THREAD

**Issue by dreamsyntax** [igorseabra4/HeroesPowerPlant#47]
* Currently spline editing works so long as the total number of splines and vertices remains the same as the original level. Verts can be increased on the final spline.
* If additional splines are added or removed, the game breaks, unless it is the final spline with no successive entries- but not for all cases.

**Comment by dreamsyntax** [comment]
Issue seems to be related to how we are parsing and saving the file

0201 Default:
![image](https://user-images.githubusercontent.com/14857235/235262231-468a4760-725f-4fe7-8b53-57d853b35731.png)

0201 Valid:
![image](https://user-images.githubusercontent.com/14857235/235262300-b2c2bd6d-8088-47db-b695-8833076b7cbd.png)

0201 Invalid:
![image](https://user-images.githubusercontent.com/14857235/235262322-c72f0c9c-3900-4496-b6fb-002c27e913a1.png)


Additionally,

If we delete in-between non-last spline causes issues. Seems like an issue of how we are calculating offsets. It will actually break, preventing HPP from reading the spline again.

**Comment by dreamsyntax** [comment]
Breaks on strncpy in-game. Definitely offset issue
![image](https://user-images.githubusercontent.com/14857235/235262629-e438a6b9-e884-409f-a54b-8dda6cdd3cc0.png)

**Comment by dreamsyntax** [comment]
```
vert = 1C? Too big, doesnt matter

vert = 0x7 per vert? [ for 5 short 3 bytes? ] | vert 8

Confirmed:
Has no relation to self's vertex count
Sec5Bytes has relation to prior spline (only)'s vertex count
Strings in prior spline has no relation


0 entry = 67 (0x43) EXCEPT for spline 1
When reaching more than vertex 7 (8 and up)
Start as 0x80 for Byte1, and count in Section2

Current Sec5Bytes

0 = 69 (0x45)
2 = 83 (0x53)
3 = 91 (0x5B)
4 = 99 (0x63)
5 = 107 (0x6B) [stg0501_ob_010]
5 = 107 (0x6B) [stg0501_cc_jn_172]
6 = 115 (0x73)
7 = 123 (0x7B)
8 = 128 (0x80) 67 (0x43)

10 = 128 (0x80) 83 (0x53)
11 = 128 (0x80) 91 (0x5B)
12 = 128 (0x80) 99 (0x63)
13 = 128 (0x80) 107 (0x6B)
14 = 128 (0x80) 115 (0x73)
15 = 128 123
17 = 128 (0x80) 139 (0x8B)
24 = 128 (0x80) 195 (0xC3)


65 = 130 (0x82) 11 (0xB)

81 = 

93 = 130 (0x82) 235 (0xEB)

210 = 136 (0x86) 147 (0x93)
339 = 138 (0x8A) 155 (0x9B)
401 = 140 (0x8C) 139 (0x8B)
It's called
"POF0"
offset table that Billy/Aqua uses
```

https://github.com/Shadowth117/PSO2-Aqua-Library/blob/ff53b0b1e683c0504082d31181adadbf36ec825a/AquaModelLibrary.Data/Ninja/POF0.cs

**Comment by Shadowth117** [comment]
https://github.com/igorseabra4/HeroesPowerPlant/pull/57
should solve this

**Comment by dreamsyntax** [comment]
Sec5/POF0 seems to be working properly.
Central City still can't save, and after further testing the issue remaining is probably padding related.

In Cryptic Castle with new changes:
Adding 1,2 splines works 
Adding 3 splines breaks
![image](https://github.com/user-attachments/assets/2da35e19-87e8-4df9-929b-974b3f000c5a)
Adding 4 splines works again
![image](https://github.com/user-attachments/assets/e6ed2619-99e7-4adf-bbca-8d32ea129c3e)

Likely related to the Black Bull (412) hardcoded padding thing - should re-look into padding.


When attempting to re-open the stage with the 3 spline scenario, HPP also cannot (just like the Black Bull case)
![image](https://github.com/user-attachments/assets/5f51bd50-8e6e-43a2-ba2f-8e0ab6d3b794)


Re-opening with the 4 splines works as expected.
